name: Publish package
on:
  push:
    tags:
      - "*"
jobs:
  package:
    runs-on: ubuntu-latest
    name: Test, build, and publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make test
